# -*- coding: utf-8 -*-
"""dictionaries

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JDqcSIlhXe-Bbyz3M_MCnBnq9t_p-7vq
"""

## Create a program that will print only the names of the people who live in Chicago. Use a list comprehension
persons = {
    'Danny':'New York',
    'Ben':'New Jersey',
    'Bob':'Chicago',
    'Tom':'Houston',
    'Sam':'Pheonix',
    'Tim':'Philadelphia',
    'Nancy':'Chicago'
}
#list comprehension
print([name for name,city in persons.items() if city == 'Chicago'])

## Given a dictionary, create a new dictionary where keys and values are swapped
original = {'Math':'Alice', 'Science':'Bob', 'History':'Charlie'}
#create a new dictionary
swapped = {v:k for k,v in original.items()}
print(swapped)

## Create a program to select only employees in the sales deparment in this nested dictionary; you can filter based on
## certain conditions within the inner dictionaries
employees = {
    'Alice':{'age':30, 'department':'sales'},
    'Bob':{'age':30, 'department':'marketing'},
    'Charlie':{'age':28, 'department':'sales'},
    'Daisy':{'age':22, 'department':'IT'}
}
#new dictionary
sales_employees = {name: info for name, info in employees.items() if info['department'] == 'sales'}
print(sales_employees)

## Create a program to combine two dictionaries, summing values for common keys
dict1 = {'a':10, 'b':20, 'c':30}
dict2 = {'b':15, 'c':5, 'd':50}

combined = {k: dict1.get(k, 0) + dict2.get(k, 0) for k in set(dict1) | set(dict2)}
print(combined)

## Create a program to store friend's name and birthdate in a dictionary object using input(). Also ensures that
## the birthday is entered in the correct YYY-MM-DD format
#empty dictionary
birthdays = {}

#adding a birthday
def add_birthday():
  name = input("Enter a friend's name: ")
  birthday = input("Enter their birthday (YYYY-MM-DD): ")
  birthdays[name] = birthday
  print(f"{name}'s birthday has been added.\n")
  main_menu()

#viewing a birthday
def view_birthday():
  name = input("Enter a friend's name: ")
  if name in birthdays:
    print(f"\n{name}'s birthday is {birthdays[name]}.")
    main_menu()
  else:
    print(f"{name} is not in the birthday list.")
    main_menu()

#displaying all birthdays
def display_birthdays():
  print("\nFriends' Birthdays:")
  for name in birthdays:
    birthday = birthdays[name]
    print(f"{name}: {birthday}")
  print("\n")
  main_menu()

#main menu
def main_menu():
  print("Birthday Manager")
  print("1. Add a birthday")
  print("2. View a birthday")
  print("3. Display all birthdays")
  print("4. Exit")

  choice = input("Enter your choice (1-4):")
  if choice == '1':
    add_birthday()
  elif choice == '2':
    view_birthday()
  elif choice == '3':
    display_birthdays()
  elif choice == '4':
    print("Goodbye!")
  else:
    print("Invalid choice. Please try again.")
    main_menu()

# create main_menu() function that offers a menu to let the user add, view, or exit
main_menu()