# -*- coding: utf-8 -*-
"""sets

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dcfbbvk54yRSZTHZrFJLNlKBd_G1HZRM
"""

## Create a program that demonstrates various set operations
baseball = set(['Jodi', 'Carmen', 'Aida', 'Alicia'])
basketball = set(['Eva', 'Carmen', 'Alicia', 'Sarah'])

#display all members of the baseball
print("The following students are on the baseball team:")
for item in baseball:
    print(item)

#display members of the basketball
print("\nThe following students are on the basketball team:")
for item in basketball:
    print(item)

#display members of both teams
print("\nThe following students are on both teams:")
for item in baseball.intersection(basketball):
    print(item)

#display students that play either baseball or basketball
print("\nThe following students play either baseball or basketball:")
for item in baseball.union(basketball):
    print(item)

#display students that play baseball, but not basketball
print("\nThe following students play baseball, but not basketball:")
for item in baseball.difference(basketball):
    print(item)

#display students that play basketball, but not baseball
print("\nThe following students play basketball, but not baseball:")
for item in basketball.difference(baseball):
    print(item)

#display students that play one sport, but not both
print("\nThe following students play one sport, but not both:")
for item in baseball.symmetric_difference(basketball):
    print(item)